[package]
name = "focus-time"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.20", features = ["derive"] }
ctrlc = "3.4.5"
env_logger = "0.11.5"
log = "0.4.22"
swayipc-async = "2.0.4"

tokio = { version = "1.41.1", features = ["full"] }
zbus = "5.1.1"
