[package]
name = "focus-time"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
ctrlc = "3.4.5"

tokio = { version = "1.41.1", features = ["full"] }
zbus = "5.1.1"
